spring.application.name=NutrifyShop
spring.data.mongodb.uri=mongodb+srv://hariprasad1307:hariprasad1307@practicereact.z8nazgl.mongodb.net/nutritionshops?retryWrites=true&w=majority&appName=practicereact
